### ISSUE TITLE
Handling real numbers

### ISSUE THREAD

**Issue by DanLionKing** [open-source-patterns/nanojsonc#2]
Hello.

Incorrect handling of real numbers when parsing JSON. For example. If the value of the "age" key contains a real number, then the callback function will always contain only the integer part of the number.
Example of an incorrectly processed JSON file:
{
  "name": {
    "first": "John",
    "last": "Doe"
  },
  "age": 30.5,
  "phone": null,
  "isStudent": false,
  "isEmployed": true,
  "hobbies": ["Reading", "Hiking", "Cooking"],
  "address": {
    "street": "123 Main St",
    "city": "Asgard",
    "state": "CA",
    "zip": "12345"
  },
  "children": [
    {
      "name": {
        "first": "Janie",
        "last": "Doe"
      },
      "age": 13.5
    },
    {
      "name": {
        "first": "Johnny",
        "last": "Doe"
      },
      "age": 14.5
    }
  ]
}

**Comment by saadshams** [comment]
@the-maazu Can you please handle this

**Comment by saadshams** [comment]
Added support for parsing negative and floating-point numbers in the latest release 1.1.0

**Comment by DanLionKing** [comment]
> Added support for parsing negative and floating-point numbers in the latest release 1.1.0

To correctly support negative values, you need to add processing inside the for operator. In line 173 of file object.c and line 159 of file array.c.

**Comment by saadshams** [comment]
@DanLionKing Once a number and a negative sign are detected, the for loop continues parsing until it reaches the end of the number. Could you provide more details about your test case for clarification?
