### ISSUE TITLE
Compiling in Debug mode fails because of -ansi flag

### ISSUE THREAD

**Issue by pnorbert** [open-source-patterns/nanojsonc#3]
Hi, I am trying to compile a project that downloads and builds nanojsonc on the fly. I need to build that project in Debug mode but that leads to compiling errors of nanojsonc. If I remove the -ansi flag added to the compile options when BUILD_TESTS is ON (or if I specify BUILD_TESTS=OFF for cmake), then I can build this. 

However, since the -ansi flag is not working, maybe you can just remove it? Or is there a flag the parent project is missing for the C language?

This is GCC 13.2 but had the same issue on Ubuntu 20.04 with GCC 9.4. 
We download tag 1.0.0
Issue is with line https://github.com/open-source-patterns/nanojsonc/blob/4d475d1efe39b3f8f4d4d5a92bb99a8269ffa578/CMakeLists.txt#L62

Thanks
Norbert

```
[ 55%] Building C object _deps/nanojsonc-build/CMakeFiles/nanojsonc.dir/src/object.c.o
In file included from build.ub24/_deps/nanojsonc-src/src/object.c:36:
build.ub24/_deps/nanojsonc-src/include/parser.h:152:8: error: extra tokens at end of #endif directive [-Werror=endif-labels]
  152 | #endif //NANOJSONC_PARSER_H
      |        ^
build.ub24/_deps/nanojsonc-src/src/object.c: In function ‘nanojsonc_parse_object’:
build.ub24/_deps/nanojsonc-src/src/object.c:68:72: error: C++ style comments are not allowed in ISO C90
   68 |     for (cursor = start; *cursor != '\0' && *cursor != '{'; cursor++); // begin brace
      |                                                                        ^
build.ub24/_deps/nanojsonc-src/src/object.c:68:72: note: (this will be reported only once per input file)
build.ub24/_deps/nanojsonc-src/src/object.c:102:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  102 |             for (int depth = 0; *cursor != '\0' && (depth > 1 || *cursor != '}'); cursor++) { // deep nested objects
      |             ^~~
build.ub24/_deps/nanojsonc-src/src/object.c:102:13: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
build.ub24/_deps/nanojsonc-src/src/object.c:111:17: error: implicit declaration of function ‘snprintf’ [-Werror=implicit-function-declaration]
  111 |             if (snprintf(subKey, NANOJSONC_KEY_SIZE, "%s[%s]", parent, key) >= NANOJSONC_KEY_SIZE) { // parentKey with childKey
      |                 ^~~~~~~~
build.ub24/_deps/nanojsonc-src/src/object.c:40:1: note: ‘snprintf’ is defined in header ‘<stdio.h>’; did you forget to ‘#include <stdio.h>’?
   39 | #include <ctype.h>
  +++ |+#include <stdio.h>
   40 |
build.ub24/_deps/nanojsonc-src/src/object.c:130:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  130 |             for (int depth = 0; *cursor != '\0' && (depth > 1 || *cursor != ']'); cursor++) { // deep nested arrays
      |             ^~~
cc1: all warnings being treated as errors
```

**Comment by saadshams** [comment]
Changed to `target_compile_options(${PROJECT_NAME} PRIVATE -Werror -Wall -std=c11)` and published a new release 1.1.0
Can you test and confirm if it's working for you?

**Comment by pnorbert** [comment]
Yes, the compilation is working now, thank you. 

But I note that now the linking of the final application fails because itself is not using the sanitizer flags:
```
/usr/bin/ld: ../libnanojsonc.a(array.c.o): in function `nanojsonc_parse_array':
build.ub24/_deps/nanojsonc-src/src/array.c:66:(.text+0x2c3): undefined reference to `__ubsan_handle_pointer_overflow_abort'
```
So I still have to force not to build the tests (`cmake ... BUILD_TESTS=OFF ...`). Maybe this could be an optional setting for the library instead of turning BUILD_TESTS=ON by default if not provided?

**Comment by saadshams** [comment]
Updated CMake and introduced flags for Sanitization and Test. Let me know.

**Comment by pnorbert** [comment]
Thank you. Your changes fixed all of my issues.

**Comment by saadshams** [comment]
Great. Can you publish an open-source minimalist example around this on your github?

> I am trying to compile a project that downloads and builds nanojsonc on the fly

**Comment by pnorbert** [comment]
Unfortunately it's not my project, so I cannot do that.

**Comment by saadshams** [comment]
oh no, I didn't mean to publish the project you are working, another project as a minimalistic example to understand your use case. Are you git cloning or making a network call to download the dependency?

Just you know, we have vcpkg integrated, that means project can download the dependency on the fly, compile and link. See the readme for Installation: VCPKG

**Comment by SamHerts** [comment]
@saadshams There is an open source example being utilized right here, which, I believe, would have the same issues with compiling in debug mode. I have not tried recreating this bug though.

https://github.com/MichaelBrim/tedium/blob/main/configurator/CMakeLists.txt

**Comment by saadshams** [comment]
@SamHerts I recently pushed 1.1.0 and this should solve the problem.
